### ISSUE TITLE
What is the result?

### ISSUE THREAD

**Issue by jerone** [gabrielrobert/xavtool#7]
Very interesting tool!

I see in the readme that you support:

*    Info.plist
*    AndroidManifest.xml
*    Package.appxmanifest

But it does not specify what will be used and result into version code and version name/string.
As different OS's have different requirements.

**Comment by gabrielrobert** [comment]
Hey @jerone, thank you for your feedback. 

I just committed this https://github.com/gabrielrobert/xavtool#results. Can you tell me if it's more clear for you?

**Comment by jerone** [comment]
Perfect!
