### ISSUE TITLE
Possible bug in Android versionCode

### ISSUE THREAD

**Issue by jerone** [gabrielrobert/xavtool#8]
I think I've identified a possible bug with Android...

Releasing the app with version 1.99.1 results in `android:versionCode="1991"`. Releasing a new major version of the app with version 2.0.0 will result in a **lower** `android:versionCode="200"`. Which is not correct.

Semver doesn't specify a limit of a version number, but releasing more then 99 patches for example will probably never happen in our opinion. But releasing with 11, 12, 13 is a real possibility. That's why we use the optional zero to create the `android:versionCode`.

Using the previous example again; releasing the app with version 1.99.1 results in `android:versionCode="019901"` and then releasing 2.0.0 will result in `android:versionCode="020000"` (which is higher again).

And because Android requires an integer, we increase the number with 1000000, resulting in `android:versionCode="1019901"` and `android:versionCode="1020000"`.

**Comment by gabrielrobert** [comment]
Hey @jerone, your help is greatly appreciated. You're right. I just updated some logic, take a look at my results:

`1.99.1` = `1990100`
`2.0.0` = `2000000`
`0.0.0` = `0`

```
versionCode = (major * 1000000) + (minor * 10000) + (patch * 100)
```

You can see the implementation of this right here -> #9.

**Comment by jerone** [comment]
Yes, exactly!

Any plans to convert this to an VSTS task?

_P.s. don't forget to update your readme 😄_

**Comment by gabrielrobert** [comment]
@jerone Just created #12 regarding VSTS. Concerning the readme, I just updated it :)
